const motorout = {
    "quotationid": null,
    "customerid": null,
    "agentid": null,
    "product_id": null,
    "coverage_id": null,
    "region_id": null,
    "inception_date": null,
    "end_date": null,
    "sum_insured_1": null,
    "sum_insured_2": null,
    "sum_insured_3": null,
    "sum_insured_4": null,
    "sum_insured_5": null,
    "total_payable": null,
    "discount_pct": null,
    "total_discount": null,
    "total_premium": null,
    "total_stamp_duty": null,
    "status": null,
    "policyNo": null,
    "ANO": null,
    "Remarks": null,
    "vehicle_detail": {},
    "customer_detail" : {
        "name": null,
        "email": null,
        "id_number": null,
        "id_type": null,
        "id_citizenship": null,
        "telephone_number": null,
        "gender": null,
        "zipcode": null,
        "address_1": null,
        "birth_date": null,
        "city" : null
      },
      "premium_details":[]
}

module.exports = motorout